name: Node.js Package TEST
on:
  push:
    branches: [main]
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - run : echo "hello" >> test.txt  /home/var/lib/
      - name: Cache something
        uses: actions/cache@v2
        with:
          path: test.txt
          key: ${{ runner.os }}-test-cache-${{ hashFiles('**/test.txt') }}
          restore-keys: |
            ${{ runner.os }}-test-cache-
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  test-cache:
    runs-on: ubuntu-latest
    steps: 
      - name: Cache something
        uses: actions/cache@v2
        with:
          path: test.txt
          key: ${{ runner.os }}-test-cache-${{ hashFiles('**/test.txt') }}
          restore-keys: |
            ${{ runner.os }}-test-cache-
      - run: cat test.txt
